config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
	  get :following, :followers
	end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :microposts, only: [:create, :destroy]
  
  resources :relationships, only: [:create, :destroy]
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  root to: 'static_pages#home'
  
  match '/signup', to: 'users#new'

  match '/help', to: 'static_pages#help'
  
  match '/about', to: 'static_pages#about'
  
  match '/contact', to: 'static_pages#contact'
  
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
	  @micropost = current_user.microposts.build
	  @feed_items = current_user.feed.paginate(page: params[:page])
	end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
 This is a project to learn about Ruby on Rails application development.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Rus about the sample app.
</p>

app/views/static_pages/help.html.erb
<% provide(:title,'Help') %>
<h1>Help</h1>
<p>
 Get help page for the Sample Application.
</p>
</html>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
	  <section>
	    <%= render 'shared/user_info' %>
	  </section>
	  <section>
	    <%= render 'shared/stats' %>
	  </section>
	  <section>
	    <%= render 'shared/micropost_form' %>
	  </section>
	</aside>
	<div class="span8">
	  <h3>Micropost Feed</h3>
	  <%= render 'shared/feed' %>
	</div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>
    <h2>
      This is the home page for the Sample Application.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>
  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>